name: "Seed infrastructure links"
description:
  "Seeds infrastructure links needed in e2e tests"

runs:
  using: "composite"
  steps:
    - name: Set up PostgreSQL client
      shell: bash
      run: |
        sudo apt-get -yqq install postgresql-client

    - name: Fetch infrastructure link dump
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/HSLdevcom/jore4-ui/main/test-db-manager/src/dumps/infraLinks/infraLinks.sql \
          -o infraLinks.sql

    - name: Seed db1 with infrastructure links
      shell: bash
      run: |
        psql postgresql://dbadmin:adminpassword@localhost:6532/jore4e2e < infraLinks.sql

    - name: Seed db2 with infrastructure links
      shell: bash
      run: |
        psql postgresql://dbadmin:adminpassword@localhost:6533/jore4e2e < infraLinks.sql

    - name: Seed db3 with infrastructure links
      shell: bash
      run: |
        psql postgresql://dbadmin:adminpassword@localhost:6534/jore4e2e < infraLinks.sql

    - name: Seed db4 with infrastructure links
      shell: bash
      run: |
        psql postgresql://dbadmin:adminpassword@localhost:6432/jore4e2e < infraLinks.sql
