name: "Seed infrastructure links"
description:
  "Seeds infrastructure links needed in e2e tests"
inputs:
  db_connection_string:
    description: Database connection string
    required: false
    default: "postgresql://dbadmin:adminpassword@localhost:5432/jore4e2e"

runs:
  using: "composite"
  steps:
    - name: Fetch infrastructure link dump
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/HSLdevcom/jore4-ui/main/test-db-manager/src/dumps/infraLinks/infraLinks.sql \
          -o infraLinks.sql

    - name: Verify that testdb is up, running and migrated
      uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
      with:
        command: "[[ $(docker exec testdb psql ${{ inputs.db_connection_string }} -AXqtc \"SELECT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'infrastructure_network' AND tablename = 'infrastructure_link');\") = \"t\" ]]"
        # it takes a while for the database to start
        retries: 50

    - name: Verify that testdb-e2e1 is up, running and migrated
      uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
      with:
        command: "[[ $(docker exec testdb-e2e1 psql ${{ inputs.db_connection_string }} -AXqtc \"SELECT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'infrastructure_network' AND tablename = 'infrastructure_link');\") = \"t\" ]]"
        # it takes a while for the database to start
        retries: 50
    
    - name: Verify that testdb-e2e2 is up, running and migrated
      uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
      with:
        command: "[[ $(docker exec testdb-e2e2 psql ${{ inputs.db_connection_string }} -AXqtc \"SELECT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'infrastructure_network' AND tablename = 'infrastructure_link');\") = \"t\" ]]"
        # it takes a while for the database to start
        retries: 50

    - name: Verify that testdb-e2e3 is up, running and migrated
      uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
      with:
        command: "[[ $(docker exec testdb-e2e3 psql ${{ inputs.db_connection_string }} -AXqtc \"SELECT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'infrastructure_network' AND tablename = 'infrastructure_link');\") = \"t\" ]]"
        # it takes a while for the database to start
        retries: 50

    - name: Seed db1 with infrastructure links
      shell: bash
      run: |
        docker exec -i testdb psql ${{ inputs.db_connection_string }} < infraLinks.sql

    - name: Seed db2 with infrastructure links
      shell: bash
      run: |
        docker exec -i testdb-e2e1 psql ${{ inputs.db_connection_string }} < infraLinks.sql

    - name: Seed db3 with infrastructure links
      shell: bash
      run: |
        docker exec -i testdb-e2e2 psql ${{ inputs.db_connection_string }} < infraLinks.sql

    - name: Seed db4 with infrastructure links
      shell: bash
      run: |
        docker exec -i testdb-e2e3 psql ${{ inputs.db_connection_string }} < infraLinks.sql
