name: "E2E Cypress tests"
description:
  "Runs cypress e2e tests. It assumes that the cypress container itself is
  already available and running, e.g. through setup-e2e-action"
inputs:
  test-tags:
    description:
      Specify a string of tags for tests to be run in format '@smoke'. To
      specify multiple tags, use format '@routes @smoke'. To run all tests, set
      it to ''.
    required: false
    default: ""
  video:
    description:
      Turn video on or off. Supported values are 'true' and 'false'.
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Run the tests
      run: |
        docker exec \
          -e TEST_TAGS="${{ inputs.test-tags }}" \
          -e TEST_VIDEO="${{ inputs.video }}" \
          cypress /e2e/cypress/run_cypress_in_4K_xvfb.sh
      shell: bash

    - name: Retrieve test reports from container
      # should be run even if the tests fail
      if: always()
      run: |
        docker cp cypress:/e2e/cypress/reports ${{ github.workspace }}/test-reports || echo "No reports"
      shell: bash

    - name: Upload test reports as an artifact
      # should be run even if the tests fail
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-docker-reports
        path: ${{ github.workspace }}/test-reports

    - name: Fail the job
      # should fail the job if the tests fail
      if: ${{ failure() }}
      run: |
        echo "E2E tests failed! See reports in the workflow's artifacts"
        exit 1
      shell: bash
