name: Check renovatebot config

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate renovatebot config
    runs-on: ubuntu-24.04
    steps:
      - name: Validate Renovatebot config
        uses: HSLdevcom/jore4-tools/github-actions/check-renovatebot-config@shared-check-renovatebot-config-v1
        with:
          config_file_path: renovatebot/jore4-default-preset.json5
