name: Test healthcheck action

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test-healthcheck-success:
    name: Verifies whether healthcheck action succeeds when it should
    runs-on: ubuntu-20.04

    steps:
      - name: Startup sample HTTP server
        run: docker run -p 8080:80 nginxdemos/hello

      - name: Verify that healthcheck succeeds
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          command: "curl --fail http://localhost:8080"

  test-healthcheck-fail:
    name: Verifies whether healthcheck action fails when it should
    runs-on: ubuntu-20.04

    steps:
      - name: Run healthcheck
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          command: "curl --fail http://localhost:8080"

      - name: Verify that the healthcheck has not succeeded
        if: ${{ success() }}
        run: |
          echo "Healthcheck should have failed!"
          exit 1
