name: Test run cypress tests action

on:
  push:
  pull_request:
    branches: [main]

jobs:
  run_cypress_tests:
    name: Run cypress e2e tests from docker
    runs-on: ubuntu-latest-4-cores

    steps:
      # Even though code checking is part of the "run-ci" action, it must be done separately here, because "run-ci" is located in this same repository.
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment and run e2e tests from github action
        uses: ./github-actions/run-ci
        with:
          test-tags: ""
